#!/usr/bin/env julia
# sim_lec02_coords.jl — Coordinate-grid level sets: freely falling ↔ lab frame
#
# Computes level-set curves of a coordinate transformation ξ^α(x^μ)
# between freely falling (ξ) and lab (x) coordinates in a gravitational
# tidal field generated by a softened dipole source.
#
# Physics:
#   A gravitational dipole at position (x⁰_s, x¹_s) outside the region
#   of interest generates a Newtonian potential
#
#     φ(x⁰, x¹) = p · (x¹ − x¹_s) / [(x⁰ − x⁰_s)² + (x¹ − x¹_s)² + a²]^{3/2}
#
#   The weak-field coordinate transformation (freely falling → lab) is
#
#     ξ^α(x⁰, x¹) = x^α + ε · ∂φ/∂x^α
#
#   a diffeomorphism for small enough ε.  The displacement ε·∇φ encodes
#   the tidal distortion between two neighbouring freely falling frames.
#
#   Level sets ξ^0 = c (horizontal-ish) and ξ^1 = c (vertical-ish) in
#   the (x¹, x⁰) plane are computed by Newton's method and written as
#   pgfplots-compatible .dat files.
#
# Run:  julia --project=. scripts/sim_lec02_coords.jl
# Output: latex/data/lec02_coord_*.dat

using Printf
using LinearAlgebra

const DATADIR = joinpath(@__DIR__, "..", "latex", "data")
mkpath(DATADIR)

# ── Dipole source parameters ──────────────────────────────────
# Source outside the plotting domain [0,2]×[0,2.5], offset so the
# tidal field is asymmetric (both curve families visibly distorted).
const x0s = -3.0     # time-position of source (below domain)
const x1s = -1.0     # space-position (offset far left)
const p   =  1.0     # dipole moment
const a   =  1.5     # softening length
const ε   = 12.0     # coupling (tuned for ~0.08–0.15 max deviation)

# ── Potential and gradient (analytic) ─────────────────────────
R²(x0, x1) = (x0 - x0s)^2 + (x1 - x1s)^2 + a^2

φ(x0, x1) = p * (x1 - x1s) / R²(x0, x1)^(3/2)

function ∂φ_∂x0(x0, x1)
    r2 = R²(x0, x1)
    return -3p * (x0 - x0s) * (x1 - x1s) / r2^(5/2)
end

function ∂φ_∂x1(x0, x1)
    r2 = R²(x0, x1)
    return p * ((x0 - x0s)^2 + a^2 - 2(x1 - x1s)^2) / r2^(5/2)
end

# ── Coordinate transformation ─────────────────────────────────
ξ0(x0, x1) = x0 + ε * ∂φ_∂x0(x0, x1)
ξ1(x0, x1) = x1 + ε * ∂φ_∂x1(x0, x1)

# ── Verification: diffeomorphism check ────────────────────────
# The Jacobian det(∂ξ/∂x) must be > 0 everywhere in the domain.
function jacobian(x0, x1; δ=1e-7)
    ∂ξ0_∂x0 = (ξ0(x0 + δ, x1) - ξ0(x0 - δ, x1)) / (2δ)
    ∂ξ0_∂x1 = (ξ0(x0, x1 + δ) - ξ0(x0, x1 - δ)) / (2δ)
    ∂ξ1_∂x0 = (ξ1(x0 + δ, x1) - ξ1(x0 - δ, x1)) / (2δ)
    ∂ξ1_∂x1 = (ξ1(x0, x1 + δ) - ξ1(x0, x1 - δ)) / (2δ)
    return ∂ξ0_∂x0 * ∂ξ1_∂x1 - ∂ξ0_∂x1 * ∂ξ1_∂x0
end

let
    jmin = Inf
    for x0 in range(0, 2.5, length=60), x1 in range(0, 2.0, length=60)
        jmin = min(jmin, jacobian(x0, x1))
    end
    @printf("Jacobian min over domain: %.6f  (must be > 0)\n", jmin)
    @assert jmin > 0.1 "ε too large — transformation is not a diffeomorphism!"
end

# ── Newton solve for implicit level sets ──────────────────────

"""
    solve_xi0(c, x1; x0_init, tol, maxiter) → x0

Solve ξ⁰(x⁰, x¹) = c for x⁰ at fixed x¹, by Newton's method.
"""
function solve_xi0(c, x1; x0_init=c, tol=1e-12, maxiter=30)
    x0 = x0_init
    for _ in 1:maxiter
        f = ξ0(x0, x1) - c
        abs(f) < tol && return x0
        δ = 1e-8
        fp = (ξ0(x0 + δ, x1) - ξ0(x0 - δ, x1)) / (2δ)
        x0 -= f / fp
    end
    return x0
end

"""
    solve_xi1(c, x0; x1_init, tol, maxiter) → x1

Solve ξ¹(x⁰, x¹) = c for x¹ at fixed x⁰, by Newton's method.
"""
function solve_xi1(c, x0; x1_init=c, tol=1e-12, maxiter=30)
    x1 = x1_init
    for _ in 1:maxiter
        f = ξ1(x0, x1) - c
        abs(f) < tol && return x1
        δ = 1e-8
        fp = (ξ1(x0, x1 + δ) - ξ1(x0, x1 - δ)) / (2δ)
        x1 -= f / fp
    end
    return x1
end

# ── Compute level sets ────────────────────────────────────────
const NPTS   = 80
const levels = [0.5, 1.0, 1.5, 2.0]

# Plotting domain (matches the TikZ axes)
const x0_lo, x0_hi = 0.0, 2.0    # vertical range (time)
const x1_lo, x1_hi = 0.0, 2.0    # horizontal range (space)

println("\nHorizontal curves  (ξ⁰ = const):")
for (i, c) in enumerate(levels)
    xs = range(x1_lo, x1_hi, length=NPTS)
    open(joinpath(DATADIR, "lec02_coord_h$i.dat"), "w") do io
        @printf(io, "%% x1  x0   (ξ⁰ = %.1f level set)\n", c)
        x0_prev = c
        for x1 in xs
            x0 = solve_xi0(c, x1; x0_init=x0_prev)
            @printf(io, "%.8f  %.8f\n", x1, x0)
            x0_prev = x0
        end
    end
    # Report deviations at endpoints and midpoint
    x0_left  = solve_xi0(c, x1_lo)
    x0_mid   = solve_xi0(c, 1.0)
    x0_right = solve_xi0(c, x1_hi)
    @printf("  ξ⁰ = %.1f:  left %+.4f  mid %+.4f  right %+.4f\n",
            c, x0_left - c, x0_mid - c, x0_right - c)
end

println("\nVertical curves  (ξ¹ = const):")
for (i, c) in enumerate(levels)
    xs = range(x0_lo, x0_hi, length=NPTS)
    open(joinpath(DATADIR, "lec02_coord_v$i.dat"), "w") do io
        @printf(io, "%% x1  x0   (ξ¹ = %.1f level set)\n", c)
        x1_prev = c
        for x0 in xs
            x1 = solve_xi1(c, x0; x1_init=x1_prev)
            @printf(io, "%.8f  %.8f\n", x1, x0)
            x1_prev = x1
        end
    end
    x1_bot = solve_xi1(c, x0_lo)
    x1_mid = solve_xi1(c, 1.0)
    x1_top = solve_xi1(c, x0_hi)
    @printf("  ξ¹ = %.1f:  bot %+.4f  mid %+.4f  top %+.4f\n",
            c, x1_bot - c, x1_mid - c, x1_top - c)
end

# ── Verification: round-trip ──────────────────────────────────
# Check that ξ(x) = c is satisfied by the computed (x0, x1) pairs.
println("\nRound-trip verification (max |ξ(x) - c|):")
let
    max_err_h = 0.0
    max_err_v = 0.0
    for (_, c) in enumerate(levels)
        for x1 in range(x1_lo, x1_hi, length=20)
            x0 = solve_xi0(c, x1)
            max_err_h = max(max_err_h, abs(ξ0(x0, x1) - c))
        end
        for x0 in range(x0_lo, x0_hi, length=20)
            x1 = solve_xi1(c, x0)
            max_err_v = max(max_err_v, abs(ξ1(x0, x1) - c))
        end
    end
    @printf("  Horizontal: %.2e\n  Vertical:   %.2e\n", max_err_h, max_err_v)
    @assert max_err_h < 1e-10 "Horizontal level sets failed verification"
    @assert max_err_v < 1e-10 "Vertical level sets failed verification"
end

println("\nDone.  Files in $DATADIR")
